'''
    ThunderGate - an open source toolkit for PCI bus exploration
    Copyright (C) 2015-2016  Saul St. John

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

# cabi - the C ABI the Linux backend of ThunderGate talks to.
#
# This hand-written module replaces the old clib.py, which was generated by
# the long-dead h2xml/xml2py (ctypeslib, Python 2 only). It binds the handful
# of libc calls, the mmap / VFIO constants, and the VFIO ioctl ABI structs
# that the Linux interface and memory-manager modules use.
#
# Linux-only in practice (like the clib.py it replaces), but written so it
# imports cleanly anywhere -- libc symbols absent on the host bind to None.

import ctypes
from ctypes import *  # noqa: F401,F403  -- re-exported as c.sizeof, c.cast, ...

_libc = ctypes.CDLL(None, use_errno=True)


def _fn(name, restype, argtypes):
    '''Bind a libc function, tolerating its absence on non-Linux hosts.'''
    f = getattr(_libc, name, None)
    if f is not None:
        f.restype = restype
        if argtypes is not None:
            f.argtypes = argtypes
    return f


# --- errno --------------------------------------------------------------------
class _Errno(object):
    @property
    def value(self):
        return ctypes.get_errno()


errno = _Errno()
EAGAIN = 11

# --- libc functions -----------------------------------------------------------
_off_t = ctypes.c_long  # 64-bit on every LP64 platform we target

mmap = _fn('mmap', ctypes.c_void_p,
           [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_int,
            ctypes.c_int, ctypes.c_int, _off_t])
mmap64 = mmap  # 64-bit off_t: mmap and mmap64 are equivalent
munmap = _fn('munmap', ctypes.c_int, [ctypes.c_void_p, ctypes.c_size_t])
valloc = _fn('valloc', ctypes.c_void_p, [ctypes.c_size_t])
mlock = _fn('mlock', ctypes.c_int, [ctypes.c_void_p, ctypes.c_size_t])
sysconf = _fn('sysconf', ctypes.c_long, [ctypes.c_int])
lseek64 = _fn('lseek', _off_t, [ctypes.c_int, _off_t, ctypes.c_int])
eventfd = _fn('eventfd', ctypes.c_int, [ctypes.c_uint, ctypes.c_int])
# pread/pwrite: the offset must be a 64-bit off_t -- VFIO encodes the region
# index in the high bits of the config-space offset, so it does not fit in int.
pread = _fn('pread', ctypes.c_ssize_t,
            [ctypes.c_int, ctypes.c_void_p, ctypes.c_size_t, _off_t])
pwrite = _fn('pwrite', ctypes.c_ssize_t,
             [ctypes.c_int, ctypes.c_void_p, ctypes.c_size_t, _off_t])
# ioctl is variadic; leave argtypes unset so ctypes passes structs by reference.
ioctl = _fn('ioctl', ctypes.c_int, None)

memset = ctypes.memset  # operates on an integer address, like libc memset

# --- mmap / sysconf constants (Linux, x86_64) --------------------------------
PROT_READ = 0x1
PROT_WRITE = 0x2
MAP_SHARED = 0x01
MAP_PRIVATE = 0x02
MAP_FIXED = 0x10
MAP_ANONYMOUS = 0x20
MAP_32BIT = 0x40
MAP_LOCKED = 0x2000
MAP_HUGETLB = 0x40000
MAP_HUGE_SHIFT = 26
MAP_FAILED = ctypes.c_void_p(-1).value
SEEK_SET = 0
_SC_PAGESIZE = 30

# --- net device ioctls (linux/sockios.h, linux/if.h) -------------------------
SIOCGIFFLAGS = 0x8913
SIOCSIFFLAGS = 0x8914
IFF_UP = 0x1
TUNSETIFF = 0x400454CA  # linux/if_tun.h

# --- VFIO ABI (linux/vfio.h) -------------------------------------------------
VFIO_API_VERSION = 0
VFIO_TYPE1_IOMMU = 1

_VFIO_TYPE = ord(';')
_VFIO_BASE = 100


def _IO(nr):
    # _IO(type, nr): direction and size are zero, so the encoding is simply
    # (type << 8) | nr.
    return (_VFIO_TYPE << 8) | (_VFIO_BASE + nr)


VFIO_GET_API_VERSION = _IO(0)
VFIO_CHECK_EXTENSION = _IO(1)
VFIO_SET_IOMMU = _IO(2)
VFIO_GROUP_GET_STATUS = _IO(3)
VFIO_GROUP_SET_CONTAINER = _IO(4)
VFIO_GROUP_UNSET_CONTAINER = _IO(5)
VFIO_GROUP_GET_DEVICE_FD = _IO(6)
VFIO_DEVICE_GET_INFO = _IO(7)
VFIO_DEVICE_GET_REGION_INFO = _IO(8)
VFIO_DEVICE_GET_IRQ_INFO = _IO(9)
VFIO_DEVICE_SET_IRQS = _IO(10)
VFIO_IOMMU_GET_INFO = _IO(12)
VFIO_IOMMU_MAP_DMA = _IO(13)

VFIO_GROUP_FLAGS_VIABLE = 1 << 0
VFIO_GROUP_FLAGS_CONTAINER_SET = 1 << 1

VFIO_REGION_INFO_FLAG_READ = 1 << 0
VFIO_REGION_INFO_FLAG_WRITE = 1 << 1
VFIO_REGION_INFO_FLAG_MMAP = 1 << 2
VFIO_REGION_INFO_FLAG_CAPS = 1 << 3

VFIO_IRQ_SET_DATA_NONE = 1 << 0
VFIO_IRQ_SET_DATA_BOOL = 1 << 1
VFIO_IRQ_SET_DATA_EVENTFD = 1 << 2
VFIO_IRQ_SET_ACTION_MASK = 1 << 3
VFIO_IRQ_SET_ACTION_UNMASK = 1 << 4
VFIO_IRQ_SET_ACTION_TRIGGER = 1 << 5

VFIO_DMA_MAP_FLAG_READ = 1 << 0
VFIO_DMA_MAP_FLAG_WRITE = 1 << 1

# vfio-pci region indices (enum in linux/vfio.h)
VFIO_PCI_BAR0_REGION_INDEX = 0
VFIO_PCI_BAR1_REGION_INDEX = 1
VFIO_PCI_BAR2_REGION_INDEX = 2
VFIO_PCI_BAR3_REGION_INDEX = 3
VFIO_PCI_BAR4_REGION_INDEX = 4
VFIO_PCI_BAR5_REGION_INDEX = 5
VFIO_PCI_ROM_REGION_INDEX = 6
VFIO_PCI_CONFIG_REGION_INDEX = 7

# vfio-pci interrupt indices (enum in linux/vfio.h)
VFIO_PCI_INTX_IRQ_INDEX = 0
VFIO_PCI_MSI_IRQ_INDEX = 1
VFIO_PCI_MSIX_IRQ_INDEX = 2
VFIO_PCI_ERR_IRQ_INDEX = 3
VFIO_PCI_REQ_IRQ_INDEX = 4

_u32 = ctypes.c_uint32
_u64 = ctypes.c_uint64


class vfio_group_status(ctypes.Structure):
    _fields_ = [('argsz', _u32), ('flags', _u32)]


class vfio_device_info(ctypes.Structure):
    _fields_ = [('argsz', _u32), ('flags', _u32),
                ('num_regions', _u32), ('num_irqs', _u32)]


class vfio_region_info(ctypes.Structure):
    _fields_ = [('argsz', _u32), ('flags', _u32), ('index', _u32),
                ('cap_offset', _u32), ('size', _u64), ('offset', _u64)]


class vfio_irq_info(ctypes.Structure):
    _fields_ = [('argsz', _u32), ('flags', _u32),
                ('index', _u32), ('count', _u32)]


class vfio_irq_set(ctypes.Structure):
    # 'data' is a flexible array member; callers ctypes.resize() the instance
    # to make room for the eventfd descriptor that follows 'count'.
    _fields_ = [('argsz', _u32), ('flags', _u32), ('index', _u32),
                ('start', _u32), ('count', _u32), ('data', ctypes.c_uint8 * 0)]


class vfio_iommu_type1_info(ctypes.Structure):
    _fields_ = [('argsz', _u32), ('flags', _u32), ('iova_pgsizes', _u64)]


class vfio_iommu_type1_dma_map(ctypes.Structure):
    _fields_ = [('argsz', _u32), ('flags', _u32),
                ('vaddr', _u64), ('iova', _u64), ('size', _u64)]
