/*
 *  ThunderGate - an open source toolkit for PCI bus exploration
 *  Copyright (C) 2015-2026  Saul St. John
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _MAP_H_
#define _MAP_H_

#include "mbuf.h"
#include "rcb.h"
#include "dma.h"

#include "utypes.h"
#include "pci.h"
#include "emac.h"
#include "sdi.h"
#include "sdc.h"
#include "sbds.h"
#include "sbdi.h"
#include "sbdc.h"
#include "rlp.h"
#include "rdi.h"
#include "rdc.h"
#include "rbdi.h"
#include "rbdc.h"
#include "cpmu.h"
#include "hc.h"
#include "ma.h"
#include "bufman.h"
#include "bdrdma.h"
#include "rdma.h"
#include "wdma.h"
#include "cpu.h"
#include "ftq.h"
#include "dmac.h"
#include "msi.h"
#include "grc.h"
#include "otp.h"
#include "tcp_seg_ctrl.h"
#include "nvram.h"
#include "cfg_port.h"
#include "pcie.h"
#include "bd.h"

#ifdef _MSC_VER
#define ANYSIZE_ARRAY
#else
#define ANYSIZE_ARRAY 0
#endif

/*
 * The Tigon3's fixed-address memory regions and register blocks.
 *
 * These MUST be declared `extern`. Their addresses are supplied at
 * link time from fixed.sym (generated by py/symgen.py, fed to ld via
 * -R), so no translation unit may allocate storage for them. A plain
 * (non-extern) declaration here is a tentative definition: with
 * -fcommon it usually becomes a COMMON symbol that fixed.sym resolves
 * away, but a translation unit can still emit it as a real .bss
 * object. The linker then allocates that .bss while the symbol itself
 * resolves to the fixed.sym address -- leaving dead, anonymous .bss.
 * coretx.o did exactly this: ~15 KB of dead .bss that overran the
 * 32 KB scratch-pad budget. `extern` makes them pure declarations.
 */
extern volatile u32 gencomm[300];
extern volatile struct rcb txrcb[2];
extern volatile struct sbd txbd[0x200];
extern volatile struct mbuf txmbuf0[ANYSIZE_ARRAY];
extern volatile struct mbuf txmbuf1[ANYSIZE_ARRAY];
extern volatile struct mbuf rxmbuf[ANYSIZE_ARRAY];
extern volatile u32 rom[ANYSIZE_ARRAY];
extern volatile u32 reg[ANYSIZE_ARRAY];
extern volatile u32 scratchpad[ANYSIZE_ARRAY];
extern volatile struct pci_regs pci;
extern volatile u32 hpmb[ANYSIZE_ARRAY];
extern volatile struct lpmb_regs lpmb;
extern volatile struct emac_regs emac;
extern volatile struct sdi_regs sdi;
extern volatile struct sdc_regs sdc;
extern volatile struct sbds_regs sbds;
extern volatile struct sbdi_regs sbdi;
extern volatile struct sbdc_regs sbdc;
extern volatile struct rlp_regs rlp;
extern volatile struct rdi_regs rdi;
extern volatile struct rdc_regs rdc;
extern volatile struct rbdi_regs rbdi;
extern volatile struct rbdc_regs rbdc;
extern volatile struct cpmu_regs cpmu;
extern volatile struct hc_regs hc;
extern volatile struct ma_regs ma;
extern volatile struct bufman_regs bufman;
extern volatile struct rdma_regs rdma;
extern volatile struct wdma_regs wdma;
extern volatile struct cpu_regs rxcpu;
extern volatile struct ftq_regs ftq;
extern volatile struct dmac_regs dmac;
extern volatile struct msi_regs msi;
extern volatile struct cfg_port_regs cfg_port;
extern volatile struct grc_regs grc;
extern volatile struct otp_regs otp;
extern volatile struct nvram_regs nvram;
extern volatile struct tcp_seg_ctrl_regs tcp_seg_ctrl;
extern volatile struct bdrdma_regs bdrdma;
extern volatile struct pcie_tl_regs pcie_tl;
extern volatile struct pcie_dl_regs pcie_dl;
#endif
